---
- name: MINECRAFT SERVICE | Create Unit file
  ansible.builtin.template:
    src: minecraft.service.j2
    dest: /etc/systemd/system/minecraft-{{ MCSERVER_NAME }}.service
  notify:
    - reload systemctl
