---
- name: PLUGINS | Install Vault
  ansible.builtin.get_url:
    url: "{{ VAULTPLUGIN.url }}"
    dest: /data/minecraft/{{ MCSERVER_NAME }}/
    mode: '0440'
    owner: mcuser
    group: minecraft

- name: PLUGINS | Install LuckPerms
  ansible.builtin.get_url:
    url: "{{ LUCKYPERMSPLUGIN.url }}"
    dest: /data/minecraft/{{ MCSERVER_NAME }}/
    mode: '0440'
    owner: mcuser
    group: minecraft

- name: PLUGINS | Install EssentialsX
  ansible.builtin.get_url:
    url: "{{ ESSENTIALSX.url }}"
    dest: /data/minecraft/{{ MCSERVER_NAME }}/minecraft_server_{{PAPERMC.version}}.jar
    mode: '0440'
    owner: mcuser
    group: minecraft

- name: PLUGINS | Install EssentialsXChat
  ansible.builtin.get_url:
    url: "{{ ESSENTIALSXCHAT.url }}"
    dest: /data/minecraft/{{ MCSERVER_NAME }}/minecraft_server_{{PAPERMC.version}}.jar
    mode: '0440'
    owner: mcuser
    group: minecraft

- name: PLUGINS | Install EssentialsXSpawn
  ansible.builtin.get_url:
    url: "{{ ESSENTIALSXSPAWN.url }}"
    dest: /data/minecraft/{{ MCSERVER_NAME }}/minecraft_server_{{PAPERMC.version}}.jar
    mode: '0440'
    owner: mcuser
    group: minecraft