---
# tasks file for mcserver
# 1. Update Server && Install Java
- name: Install Java
  become: true
  ansible.builtin.import_tasks: install_java.yml
# 2. Create User and Group
- name: Create Group and User
  become: true
  ansible.builtin.import_tasks: create_user_group.yml
# 3. Create Folder Directory (/data/minecraft/<SERVER>)
- name: Create Folders
  become: true
  ansible.builtin.import_tasks: create_dir.yml
# 4. Download PaperMC JAR & Accept EULA
- name: INSTALL PAPER MC
  become: true
  ansible.builtin.import_tasks: install_papermc.yml
# 5. Smile
# 6. Install as a Service
- name: Create Service for Server
  become: true
  ansible.builtin.import_tasks: create_service.yml

- name: "Flush handlers"
  meta: flush_handlers

# 7. Start Service
- name: Start Minecraft
  become: true
  ansible.builtin.service:
    name: minecraft-{{ MCSERVER_NAME }}.service
    state: started


- name: Wait for Minecraft
  ansible.builtin.pause:
    minutes: 2

# 8. Install Plugins (Vault, LuckPerms, EssentialsX, EssentialsXChat, EssentialsXSpawn)
- name: Install Plugins
  become: true
  ansible.builtin.import_tasks: install_plugins.yml

# 9. Restart Service
- name: "Flush handlers"
  meta: flush_handlers

- name: Wait for Minecraft
  ansible.builtin.pause:
    minutes: 2   

# 10. Update Config Files
- name: Update Plugin Config
  ansible.builtin.import_tasks: update_plugin_config.yml
  
# 11. Restart Service

